name: Run Actions with a Schedule
on:
  schedule:
    # Use https://crontab.guru to find the syntax for your desired schedule
    # By default, run daily at 11:15
    - cron: 15 11 * * *
  workflow_dispatch:
    # This allows you to run the action manually
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies via package-lock
        run: npm ci
      
      - name: Run default node task
        run: npm start
        env: # using environment variables
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_USER_ID: ${{ secrets.TWITTER_USER_ID }}

